# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: 'mxzheng.github.io' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Mengxin Zheng
tagline: Materials Science
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: '
My early exposure to programming using Visual Basic back in middle school sparked my interest in computer science (CS), 
making my decision of majoring in CS to solve practical engineering problems. In the first year, I have mastered 
JAVA and LINUX language and grasped modeling methods. So I transferred to materials. Materials in my university is
 TOP5 in China, which is a big appeal to me. Due to the great diversity of majors, I need to learn a lot of specialized courses.
Time is very compact. However, studying materials classes gave me immense sense of satisfaction and some courses have 
achieved excellent results.
You can <a href="./CV.pdf" target="_blank">download my resume here</a>.'

#sidebar links
email: zhengmx95@gmail.com
phone: +86 17865169886
website: mxzheng.github.io/blog #do not add http://
linkedin: mxzheng
github: mxzheng
twitter: '@mxzheng'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
